services:

  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_value:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=secret_password

volumes:
  db_value:
