services:

  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_value:/data/db
      - ./test_data:app/test_data
    env_file: .env

  bot:
    image: inferno681/rlt_test_bot:latest
    restart: always
    env_file: .env
    depends_on:
      - db

volumes:
  db_value:
